<?php
/**
 * SpDATSEARCHFETC0PersonResultTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * api.riskscreen.com
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\Client;

/**
 * SpDATSEARCHFETC0PersonResultTest Class Doc Comment
 *
 * @category    Class */
// * @description SpDATSEARCHFETC0PersonResult
/**
 * @package     Swagger\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class SpDATSEARCHFETC0PersonResultTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "SpDATSEARCHFETC0PersonResult"
     */
    public function testSpDATSEARCHFETC0PersonResult()
    {
    }

    /**
     * Test attribute "daen_id"
     */
    public function testPropertyDaenId()
    {
    }

    /**
     * Test attribute "daen_serial"
     */
    public function testPropertyDaenSerial()
    {
    }

    /**
     * Test attribute "daen_stet_id"
     */
    public function testPropertyDaenStetId()
    {
    }

    /**
     * Test attribute "daen_stet_name"
     */
    public function testPropertyDaenStetName()
    {
    }

    /**
     * Test attribute "daen_firstname"
     */
    public function testPropertyDaenFirstname()
    {
    }

    /**
     * Test attribute "daen_firstnamejcb"
     */
    public function testPropertyDaenFirstnamejcb()
    {
    }

    /**
     * Test attribute "daen_middlename"
     */
    public function testPropertyDaenMiddlename()
    {
    }

    /**
     * Test attribute "daen_middlenamejcb"
     */
    public function testPropertyDaenMiddlenamejcb()
    {
    }

    /**
     * Test attribute "daen_lastname"
     */
    public function testPropertyDaenLastname()
    {
    }

    /**
     * Test attribute "daen_lastnamejcb"
     */
    public function testPropertyDaenLastnamejcb()
    {
    }

    /**
     * Test attribute "daen_fullname"
     */
    public function testPropertyDaenFullname()
    {
    }

    /**
     * Test attribute "daen_title"
     */
    public function testPropertyDaenTitle()
    {
    }

    /**
     * Test attribute "daen_suffix"
     */
    public function testPropertyDaenSuffix()
    {
    }

    /**
     * Test attribute "daen_partition"
     */
    public function testPropertyDaenPartition()
    {
    }

    /**
     * Test attribute "daen_reverse"
     */
    public function testPropertyDaenReverse()
    {
    }

    /**
     * Test attribute "daen_ispep"
     */
    public function testPropertyDaenIspep()
    {
    }

    /**
     * Test attribute "daen_isrca"
     */
    public function testPropertyDaenIsrca()
    {
    }

    /**
     * Test attribute "daen_iswbl"
     */
    public function testPropertyDaenIswbl()
    {
    }

    /**
     * Test attribute "daen_issan"
     */
    public function testPropertyDaenIssan()
    {
    }

    /**
     * Test attribute "daen_isavm"
     */
    public function testPropertyDaenIsavm()
    {
    }

    /**
     * Test attribute "daen_isunk"
     */
    public function testPropertyDaenIsunk()
    {
    }
}
