<?php
/**
 * WebSearchPersonTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * api.riskscreen.com
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\Client;

/**
 * WebSearchPersonTest Class Doc Comment
 *
 * @category    Class */
// * @description WebSearchPerson
/**
 * @package     Swagger\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class WebSearchPersonTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "WebSearchPerson"
     */
    public function testWebSearchPerson()
    {
    }

    /**
     * Test attribute "first_name"
     */
    public function testPropertyFirstName()
    {
    }

    /**
     * Test attribute "last_name"
     */
    public function testPropertyLastName()
    {
    }

    /**
     * Test attribute "middle_names"
     */
    public function testPropertyMiddleNames()
    {
    }

    /**
     * Test attribute "last_name_accuracy_percent"
     */
    public function testPropertyLastNameAccuracyPercent()
    {
    }

    /**
     * Test attribute "first_name_accuracy_percent"
     */
    public function testPropertyFirstNameAccuracyPercent()
    {
    }

    /**
     * Test attribute "middle_names_accuracy_percent"
     */
    public function testPropertyMiddleNamesAccuracyPercent()
    {
    }

    /**
     * Test attribute "reverse_name_search"
     */
    public function testPropertyReverseNameSearch()
    {
    }

    /**
     * Test attribute "search_pep"
     */
    public function testPropertySearchPep()
    {
    }

    /**
     * Test attribute "search_ref"
     */
    public function testPropertySearchRef()
    {
    }

    /**
     * Test attribute "search_watch_lists"
     */
    public function testPropertySearchWatchLists()
    {
    }

    /**
     * Test attribute "search_sanctions"
     */
    public function testPropertySearchSanctions()
    {
    }

    /**
     * Test attribute "display_result_details"
     */
    public function testPropertyDisplayResultDetails()
    {
    }

    /**
     * Test attribute "display_filtered_results_only"
     */
    public function testPropertyDisplayFilteredResultsOnly()
    {
    }

    /**
     * Test attribute "filters"
     */
    public function testPropertyFilters()
    {
    }
}
