<?php
/**
 * WebSearchCompanyTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * api.riskscreen.com
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.3.1
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\Client;

/**
 * WebSearchCompanyTest Class Doc Comment
 *
 * @category    Class */
// * @description WebSearchCompany
/**
 * @package     Swagger\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class WebSearchCompanyTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "WebSearchCompany"
     */
    public function testWebSearchCompany()
    {
    }

    /**
     * Test attribute "company_name"
     */
    public function testPropertyCompanyName()
    {
    }

    /**
     * Test attribute "company_name_accuracy_percent"
     */
    public function testPropertyCompanyNameAccuracyPercent()
    {
    }

    /**
     * Test attribute "search_ref"
     */
    public function testPropertySearchRef()
    {
    }

    /**
     * Test attribute "search_watch_lists"
     */
    public function testPropertySearchWatchLists()
    {
    }

    /**
     * Test attribute "search_sanctions"
     */
    public function testPropertySearchSanctions()
    {
    }

    /**
     * Test attribute "display_result_details"
     */
    public function testPropertyDisplayResultDetails()
    {
    }

    /**
     * Test attribute "display_filtered_results_only"
     */
    public function testPropertyDisplayFilteredResultsOnly()
    {
    }

    /**
     * Test attribute "filters"
     */
    public function testPropertyFilters()
    {
    }
}
